In [2]:
import pandas as pd
import numpy as np
import sys
sys.path.append(".")
import MosaEncoder
from MosaStacker import MosaTargetEncoder
# from sklearn.model_selection import StratifiedKFold
%load_ext autoreload
%autoreload

In [3]:
train = pd.read_csv("./train.csv")

In [4]:
test_enc = MosaEncoder.MosaLabelEncoder("Embarked","embarked_label")
test_enc.fit(train,[])
df_t = test_enc.transform(train)

In [5]:
df_t.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  embarked_label  
0      0         A/5 21171   7.2500   NaN        S               0  
1      0          PC 17599  71.2833   C85        C               1  
2      0  STON/O2. 3101282   7.9250   NaN        S               0  
3      0            113803  53.1000  C123        S               0  
4      0            373450   8.0500   NaN        S               0

In [10]:
tp = MosaTargetEncoder("embarked_label")
df_tt = tp.fit_trans_train(df_t,df_t["Survived"])
df_tt.head(6)

/Users/kakeru/PycharmProjects/main_env/lib/python3.7/site-packages/sklearn/model_selection/_split.py:629: FutureWarning: The default value of n_split will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(NSPLIT_WARNING, FutureWarning)


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  embarked_label  \
0      0         A/5 21171   7.2500   NaN        S               0   
1      0          PC 17599  71.2833   C85        C               1   
2      0  STON/O2. 3101282   7.9250   NaN        S               0   
3      0            113803  53.1000  C123        S               0   
4      0            373450   8.0500   NaN        S               0   
5      0            330877   8.4583   NaN        Q               2   

   embarked_label_TME  
0            0.337963  
1            0.586207  
2            0.337963  
3            0.337963  
4            0.337963  
5            0.288889

In [29]:
test_d = {}
test_d[1] = 2
test_d[None] = -1
test_d["hoge"] = -1
test_d["fuga"] = -1
print(test_d)

{1: 2, None: -1, 'hoge': -1, 'fuga': -1}


In [12]:
tp = np.zeros(len(df_tt.values))
tp[df_tt["Age"].isna()] = 1
print(tp[:10])

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [24]:
su = df_tt["Cabin"].unique()
# su.sort()
# su = su[::-1]
print(su)

[nan 'C85' 'C123' 'E46' 'G6' 'C103' 'D56' 'A6' 'C23 C25 C27' 'B78' 'D33'
 'B30' 'C52' 'B28' 'C83' 'F33' 'F G73' 'E31' 'A5' 'D10 D12' 'D26' 'C110'
 'B58 B60' 'E101' 'F E69' 'D47' 'B86' 'F2' 'C2' 'E33' 'B19' 'A7' 'C49'
 'F4' 'A32' 'B4' 'B80' 'A31' 'D36' 'D15' 'C93' 'C78' 'D35' 'C87' 'B77'
 'E67' 'B94' 'C125' 'C99' 'C118' 'D7' 'A19' 'B49' 'D' 'C22 C26' 'C106'
 'C65' 'E36' 'C54' 'B57 B59 B63 B66' 'C7' 'E34' 'C32' 'B18' 'C124' 'C91'
 'E40' 'T' 'C128' 'D37' 'B35' 'E50' 'C82' 'B96 B98' 'E10' 'E44' 'A34'
 'C104' 'C111' 'C92' 'E38' 'D21' 'E12' 'E63' 'A14' 'B37' 'C30' 'D20' 'B79'
 'E25' 'D46' 'B73' 'C95' 'B38' 'B39' 'B22' 'C86' 'C70' 'A16' 'C101' 'C68'
 'A10' 'E68' 'B41' 'A20' 'D19' 'D50' 'D9' 'A23' 'B50' 'A26' 'D48' 'E58'
 'C126' 'B71' 'B51 B53 B55' 'D49' 'B5' 'B20' 'F G63' 'C62 C64' 'E24' 'C90'
 'C45' 'E8' 'B101' 'D45' 'C46' 'D30' 'E121' 'D11' 'E77' 'F38' 'B3' 'D6'
 'B82 B84' 'D17' 'A36' 'B102' 'B69' 'E49' 'C47' 'D28' 'E17' 'A24' 'C50'
 'B42' 'C148']


In [23]:
df_tt["Age"].unique()

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [28]:
print(pd.isna(0))

False


In [31]:
hoge = np.zeros(len(df_t.values))
hoge[df_t.query("embarked_label == 2").index] = 1
print(hoge[:10])

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
